### ISSUE TITLE
bot.py truncado

### ISSUE THREAD

**Issue by SrMouraSilva** [ARiDa/telegram-bot-ru#2]
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import bot
  File "/home/paulo/Downloads/telegram-bot-ru/bot.py", line 18
    bot.sendMessage(chat_id=chat_id, text=msg, parse_mode=telegram.ParseMode.HTML)
                                                                                 ^
SyntaxError: unexpected EOF while parsing
```

**Comment by lucaspg96** [comment]
Sim, realmente houve um problema no arquivo bot.py. Commitei a versão correta
